from PySide6 import QtWidgets, QtGui, QtCore, QtOpenGLWidgets

from leftMenu import LeftMenu

class MainBody(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(MainBody, self).__init__(parent)
        self.setupUi()

        self.cur_frm = 0

    def setupUi(self):
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setObjectName("mainBody")
        self.hlyt_main_body = QtWidgets.QHBoxLayout(self)
        self.hlyt_main_body.setContentsMargins(5, 5, 0, 0)
        self.hlyt_main_body.setSpacing(0)
        self.hlyt_main_body.setObjectName("hlyt_main_body")

        ### left menu
        self.left_menu = LeftMenu(self)
        
        self.btn_viewer_tab = QtWidgets.QPushButton(self.left_menu.frame_left_menu_top)
        self.btn_viewer_tab.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_viewer_tab.setMaximumSize(QtCore.QSize(250, 16777215))
        self.btn_viewer_tab.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_viewer_tab.setStyleSheet(":open{\n"
    "    background-color:#242424;\n"
    "    border-left: 2px solid #f84119;\n"
    "}")
        self.btn_viewer_tab.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resource/icons/viewer-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_viewer_tab.setIcon(icon3)
        self.btn_viewer_tab.setCheckable(True)
        self.btn_viewer_tab.setChecked(True)
        self.btn_viewer_tab.setAutoRepeat(False)
        self.btn_viewer_tab.setDefault(False)
        self.btn_viewer_tab.setObjectName("viewer_tab_btn")

        self.btn_group_left_menu = QtWidgets.QButtonGroup(self)
        self.btn_group_left_menu.setObjectName("left_menu_btn_group")
        self.btn_group_left_menu.addButton(self.btn_viewer_tab)
        self.left_menu.vlyt_frame_left_menu_top.addWidget(self.btn_viewer_tab)
        self.btn_annotation_tab = QtWidgets.QPushButton(self.left_menu.frame_left_menu_top)
        self.btn_annotation_tab.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_annotation_tab.setMaximumSize(QtCore.QSize(250, 16777215))
        self.btn_annotation_tab.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_annotation_tab.setStyleSheet(":open{\n"
    "    background-color:#242424;\n"
    "    border-left: 2px solid #f84119;\n"
    "}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resource/icons/tag-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_annotation_tab.setIcon(icon4)
        self.btn_annotation_tab.setCheckable(True)
        self.btn_annotation_tab.setAutoDefault(False)
        self.btn_annotation_tab.setDefault(False)
        self.btn_annotation_tab.setObjectName("annotation_tab_btn")
        self.btn_group_left_menu.addButton(self.btn_annotation_tab)
        self.left_menu.vlyt_frame_left_menu_top.addWidget(self.btn_annotation_tab)

        self.btn_analysis_tab = QtWidgets.QPushButton(self.left_menu.frame_left_menu_top)
        self.btn_analysis_tab.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_analysis_tab.setMaximumSize(QtCore.QSize(250, 16777215))
        self.btn_analysis_tab.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_analysis_tab.setStyleSheet(":open{\n"
    "    background-color:#242424;\n"
    "    border-left: 2px solid #f84119;\n"
    "}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resource/icons/scatter-plot-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_analysis_tab.setIcon(icon5)
        self.btn_analysis_tab.setCheckable(True)
        self.btn_analysis_tab.setObjectName("analysisBtn")
        self.btn_group_left_menu.addButton(self.btn_analysis_tab)




        self.left_menu.vlyt_frame_left_menu_top.addWidget(self.btn_analysis_tab)
        self.left_menu.vlyt_frame_wrap.addWidget(self.left_menu.frame_left_menu_top)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.left_menu.vlyt_frame_wrap.addItem(spacerItem)
        self.frame_left_menu_bottom = QtWidgets.QFrame(self.left_menu.frame_wrap)
        self.frame_left_menu_bottom.setMaximumSize(QtCore.QSize(30, 16777215))
        self.frame_left_menu_bottom.setBaseSize(QtCore.QSize(0, 0))
        self.frame_left_menu_bottom.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left_menu_bottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left_menu_bottom.setObjectName("leftMenuFrameBottom")
        self.vlyt_frame_left_menu_bottom = QtWidgets.QVBoxLayout(self.frame_left_menu_bottom)
        self.vlyt_frame_left_menu_bottom.setContentsMargins(0, 0, 0, 0)
        self.vlyt_frame_left_menu_bottom.setSpacing(0)
        self.vlyt_frame_left_menu_bottom.setObjectName("vlytLeftMenuFrameBottom")

        self.btn_setting = QtWidgets.QPushButton(self.frame_left_menu_bottom)
        self.btn_setting.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_setting.setMaximumSize(QtCore.QSize(250, 16777215))
        self.btn_setting.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_setting.setStyleSheet(":open{\n"
    "    background-color:#242424;\n"
    "    border-left: 2px solid #f84119;\n"
    "}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resource/icons/settings-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_setting.setIcon(icon6)
        self.btn_setting.setCheckable(True)
        self.btn_setting.setObjectName("btn_setting")
        self.btn_group_left_menu.addButton(self.btn_setting)

        self.vlyt_frame_left_menu_bottom.addWidget(self.btn_setting)
        self.btn_help = QtWidgets.QPushButton(self.frame_left_menu_bottom)
        self.btn_help.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_help.setMaximumSize(QtCore.QSize(250, 16777215))
        self.btn_help.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_help.setStyleSheet(":open{\n"
    "    background-color:#242424;\n"
    "    border-left: 2px solid #f84119;\n"
    "}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resource/icons/help-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_help.setIcon(icon7)
        self.btn_help.setCheckable(True)
        self.btn_help.setObjectName("helpBtn")
        self.btn_group_left_menu.addButton(self.btn_help)
        self.vlyt_frame_left_menu_bottom.addWidget(self.btn_help)
        self.btn_about = QtWidgets.QPushButton(self.frame_left_menu_bottom)
        self.btn_about.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_about.setMaximumSize(QtCore.QSize(250, 16777215))
        self.btn_about.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_about.setStyleSheet(":open{\n"
    "    background-color:#242424;\n"
    "    border-left: 2px solid #f84119;\n"
    "}")
        self.btn_about.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resource/icons/info-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_about.setIcon(icon8)
        self.btn_about.setCheckable(True)
        self.btn_about.setChecked(False)
        self.btn_about.setAutoDefault(False)
        self.btn_about.setDefault(False)
        self.btn_about.setObjectName("aboutBtn")
        self.btn_group_left_menu.addButton(self.btn_about)
        self.vlyt_frame_left_menu_bottom.addWidget(self.btn_about)
        self.left_menu.vlyt_frame_wrap.addWidget(self.frame_left_menu_bottom)

        self.left_menu.vlyt.addWidget(self.left_menu.frame_wrap)

        self.hlyt_main_body.addWidget(self.left_menu)
        selfContent = QtWidgets.QWidget(self)
        selfContent.setObjectName("mainBodyContent")
        selfContent.setStyleSheet("background-color:#242424")
        self.vlyt_main_body_content = QtWidgets.QVBoxLayout(selfContent)
        self.vlyt_main_body_content.setObjectName("vlytMainBodyContent")

        self.stackedWidget = QtWidgets.QStackedWidget(selfContent)
        self.stackedWidget.setObjectName("stackedWidget")
        
        self.viewerPage = QtWidgets.QWidget()
        self.viewerPage.setObjectName("viewerPage")
        self.label = QtWidgets.QLabel(self.viewerPage)
        self.label.setGeometry(QtCore.QRect(270, 180, 81, 16))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.viewerPage)

        self.annotationPage = QtWidgets.QWidget()
        self.annotationPage.setObjectName("annotationPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.annotationPage)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vlytAnnotationPage = QtWidgets.QVBoxLayout()
        self.vlytAnnotationPage.setSpacing(5)
        self.vlytAnnotationPage.setObjectName("vlytAnnotationPage")
        self.annotationPageControl = QtWidgets.QTabWidget(self.annotationPage)
        self.annotationPageControl.setObjectName("annotationPageControl")
        self.tabAnnotationPageControlMain = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabAnnotationPageControlMain.sizePolicy().hasHeightForWidth())
        self.tabAnnotationPageControlMain.setSizePolicy(sizePolicy)
        self.tabAnnotationPageControlMain.setObjectName("tabAnnotationPageControlMain")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabAnnotationPageControlMain)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hlytPlayControls = QtWidgets.QHBoxLayout()
        self.hlytPlayControls.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.hlytPlayControls.setSpacing(5)
        self.hlytPlayControls.setObjectName("hlytPlayControls")
        self.hor_slider = QtWidgets.QSlider(self.tabAnnotationPageControlMain)
        self.hor_slider.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.SizeHorCursor))
        self.hor_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.hor_slider.setObjectName("horizontalSlider")
        self.hor_slider.setMaximum(0)
        self.hor_slider.valueChanged.connect(self.handleSliderValueChanged)

        self.hlytPlayControls.addWidget(self.hor_slider)
        self.hlinePlayControl1 = QtWidgets.QFrame(self.tabAnnotationPageControlMain)
        self.hlinePlayControl1.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.hlinePlayControl1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.hlinePlayControl1.setObjectName("hlinePlayControl1")
        self.hlytPlayControls.addWidget(self.hlinePlayControl1)

        self.line_edit_frm = QtWidgets.QLineEdit(self.tabAnnotationPageControlMain)
        self.line_edit_frm.setObjectName("lineEditFrame")
        self.line_edit_frm.setText(str(self.hor_slider.value()))

        self.hlytPlayControls.addWidget(self.line_edit_frm)
        self.hlinePlayControl2 = QtWidgets.QFrame(self.tabAnnotationPageControlMain)
        self.hlinePlayControl2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.hlinePlayControl2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.hlinePlayControl2.setObjectName("hlinePlayControl2")
        self.hlytPlayControls.addWidget(self.hlinePlayControl2)
        self.btnStart = QtWidgets.QPushButton(self.tabAnnotationPageControlMain)
        self.btnStart.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnStart.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("resource/icons/player-control-skip-to-start-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnStart.setIcon(icon9)
        self.btnStart.setObjectName("btnStart")
        self.hlytPlayControls.addWidget(self.btnStart)
        self.btnStepBwd = QtWidgets.QPushButton(self.tabAnnotationPageControlMain)
        self.btnStepBwd.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnStepBwd.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("resource/icons/player-control-rewind-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnStepBwd.setIcon(icon10)
        self.btnStepBwd.setIconSize(QtCore.QSize(16, 16))
        self.btnStepBwd.setObjectName("btnStepBwd")
        self.hlytPlayControls.addWidget(self.btnStepBwd)
        self.btnPause = QtWidgets.QPushButton(self.tabAnnotationPageControlMain)
        self.btnPause.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPause.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("resource/icons/player-control-pause-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPause.setIcon(icon11)
        self.btnPause.setObjectName("btnPause")
        self.hlytPlayControls.addWidget(self.btnPause)
        self.btnPlay = QtWidgets.QPushButton(self.tabAnnotationPageControlMain)
        self.btnPlay.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPlay.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("resource/icons/player-control-play-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPlay.setIcon(icon12)
        self.btnPlay.setObjectName("btnPlay")
        self.hlytPlayControls.addWidget(self.btnPlay)
        self.btnStepFwd = QtWidgets.QPushButton(self.tabAnnotationPageControlMain)
        self.btnStepFwd.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnStepFwd.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("resource/icons/player-control-fast-forward-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnStepFwd.setIcon(icon13)
        self.btnStepFwd.setObjectName("btnStepFwd")
        self.hlytPlayControls.addWidget(self.btnStepFwd)
        self.btnEnd = QtWidgets.QPushButton(self.tabAnnotationPageControlMain)
        self.btnEnd.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnEnd.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("resource/icons/player-control-end-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnEnd.setIcon(icon14)
        self.btnEnd.setObjectName("btnEnd")
        self.hlytPlayControls.addWidget(self.btnEnd)
        self.hlytPlayControls.setStretch(0, 9)
        self.horizontalLayout_2.addLayout(self.hlytPlayControls)
        self.annotationPageControl.addTab(self.tabAnnotationPageControlMain, "")
        self.tabAnnotationControlSub = QtWidgets.QWidget()
        self.tabAnnotationControlSub.setObjectName("tabAnnotationControlSub")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tabAnnotationControlSub)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.hlytViewConfig = QtWidgets.QHBoxLayout()
        self.hlytViewConfig.setObjectName("hlytViewConfig")
        self.comboBoxSensorConfig = QtWidgets.QComboBox(self.tabAnnotationControlSub)
        self.comboBoxSensorConfig.setObjectName("comboBoxSensorConfig")
        self.hlytViewConfig.addWidget(self.comboBoxSensorConfig)
        self.comboBoxDtctConfig = QtWidgets.QComboBox(self.tabAnnotationControlSub)
        self.comboBoxDtctConfig.setObjectName("comboBoxDtctConfig")
        self.hlytViewConfig.addWidget(self.comboBoxDtctConfig)
        self.comboBoxObjConfig = QtWidgets.QComboBox(self.tabAnnotationControlSub)
        self.comboBoxObjConfig.setObjectName("comboBoxObjConfig")
        self.hlytViewConfig.addWidget(self.comboBoxObjConfig)
        self.comboBoxViewConfig = QtWidgets.QComboBox(self.tabAnnotationControlSub)
        self.comboBoxViewConfig.setObjectName("comboBoxViewConfig")
        self.hlytViewConfig.addWidget(self.comboBoxViewConfig)
        self.btnPalette = QtWidgets.QPushButton(self.tabAnnotationControlSub)
        self.btnPalette.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPalette.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("resource/icons/palette-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPalette.setIcon(icon15)
        self.btnPalette.setObjectName("btnPalette")
        self.hlytViewConfig.addWidget(self.btnPalette)
        self.btnSaveConfig = QtWidgets.QPushButton(self.tabAnnotationControlSub)
        self.btnSaveConfig.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("resource/icons/save-document-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSaveConfig.setIcon(icon16)
        self.btnSaveConfig.setObjectName("btnSaveConfig")
        self.hlytViewConfig.addWidget(self.btnSaveConfig)
        self.btnLoadConfig = QtWidgets.QPushButton(self.tabAnnotationControlSub)
        self.btnLoadConfig.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("resource/icons/open-document-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnLoadConfig.setIcon(icon17)
        self.btnLoadConfig.setObjectName("btnLoadConfig")
        self.hlytViewConfig.addWidget(self.btnLoadConfig)
        self.hlytViewConfig.setStretch(0, 1)
        self.hlytViewConfig.setStretch(1, 1)
        self.hlytViewConfig.setStretch(2, 1)
        self.hlytViewConfig.setStretch(3, 1)
        self.horizontalLayout_4.addLayout(self.hlytViewConfig)
        self.annotationPageControl.addTab(self.tabAnnotationControlSub, "")
        self.vlytAnnotationPage.addWidget(self.annotationPageControl)
        self.hspltAnnotationPage = QtWidgets.QSplitter(self.annotationPage)
        self.hspltAnnotationPage.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.hspltAnnotationPage.setChildrenCollapsible(False)
        self.hspltAnnotationPage.setObjectName("hspltAnnotationPage")
        self.vsplitAnnotationPageView = QtWidgets.QSplitter(self.hspltAnnotationPage)
        self.vsplitAnnotationPageView.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.vsplitAnnotationPageView.setChildrenCollapsible(False)
        self.vsplitAnnotationPageView.setObjectName("vsplitAnnotationPageView")
        self.openGLWidget_4 = QtOpenGLWidgets.QOpenGLWidget(self.vsplitAnnotationPageView)
        self.openGLWidget_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.openGLWidget_4.setMouseTracking(False)
        self.openGLWidget_4.setObjectName("openGLWidget_4")
        self.hsplitAnnotationPageView = QtWidgets.QSplitter(self.vsplitAnnotationPageView)
        self.hsplitAnnotationPageView.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.hsplitAnnotationPageView.setChildrenCollapsible(False)
        self.hsplitAnnotationPageView.setObjectName("hsplitAnnotationPageView")

        self.openGLWidget = QtOpenGLWidgets.QOpenGLWidget(self.hsplitAnnotationPageView)
        self.openGLWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.openGLWidget.setObjectName("openGLWidget")
        self.openGLWidget_2 = QtOpenGLWidgets.QOpenGLWidget(self.hsplitAnnotationPageView)
        self.openGLWidget_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.openGLWidget_2.setObjectName("openGLWidget_2")
        self.openGLWidget_3 = QtOpenGLWidgets.QOpenGLWidget(self.hsplitAnnotationPageView)
        self.openGLWidget_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.openGLWidget_3.setObjectName("openGLWidget_3")
        self.annotationPageinfo = QtWidgets.QTabWidget(self.hspltAnnotationPage)
        self.annotationPageinfo.setObjectName("annotationPageinfo")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.annotationPageinfo.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.annotationPageinfo.addTab(self.tab_4, "")
        self.vlytAnnotationPage.addWidget(self.hspltAnnotationPage)
        self.vlytAnnotationPage.setStretch(1, 9)
        self.verticalLayout_2.addLayout(self.vlytAnnotationPage)
        self.stackedWidget.addWidget(self.annotationPage)
        self.analysisPage = QtWidgets.QWidget()
        self.analysisPage.setObjectName("analysisPage")
        self.label_3 = QtWidgets.QLabel(self.analysisPage)
        self.label_3.setGeometry(QtCore.QRect(290, 150, 131, 16))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.analysisPage)
        self.settingPage = QtWidgets.QWidget()
        self.settingPage.setObjectName("settingPage")
        self.label_4 = QtWidgets.QLabel(self.settingPage)
        self.label_4.setGeometry(QtCore.QRect(400, 190, 121, 16))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.settingPage)
        self.helpPage = QtWidgets.QWidget()
        self.helpPage.setObjectName("helpPage")
        self.label_5 = QtWidgets.QLabel(self.helpPage)
        self.label_5.setGeometry(QtCore.QRect(260, 230, 81, 16))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.helpPage)
        self.aboutPage = QtWidgets.QWidget()
        self.aboutPage.setObjectName("aboutPage")
        self.label_6 = QtWidgets.QLabel(self.aboutPage)
        self.label_6.setGeometry(QtCore.QRect(420, 260, 91, 16))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.aboutPage)
        self.vlyt_main_body_content.addWidget(self.stackedWidget)
        self.hlyt_main_body.addWidget(selfContent)
        self.rightMenu = QtWidgets.QWidget(self)
        self.rightMenu.setObjectName("rightMenu")
        self.hlyt_main_body.addWidget(self.rightMenu)

        self.stackedWidget.setCurrentIndex(1)
        self.annotationPageControl.setCurrentIndex(1)
        self.annotationPageinfo.setCurrentIndex(0)

    def retranslateUi(self, _translate):
        self.btn_viewer_tab.setText(_translate("MainWindow", "Viewer"))
        self.btn_annotation_tab.setText(_translate("MainWindow", "Annotation"))
        self.btn_analysis_tab.setText(_translate("MainWindow", "Analysis"))
        self.btn_setting.setText(_translate("MainWindow", "Setting"))
        self.btn_help.setText(_translate("MainWindow", "Help"))
        self.btn_about.setText(_translate("MainWindow", "About"))
        self.label.setText(_translate("MainWindow", "viewerPage"))
        self.annotationPageControl.setTabText(self.annotationPageControl.indexOf(self.tabAnnotationPageControlMain), _translate("MainWindow", "Play Controls"))
        self.annotationPageControl.setTabText(self.annotationPageControl.indexOf(self.tabAnnotationControlSub), _translate("MainWindow", "View Configuration"))
        self.annotationPageinfo.setTabText(self.annotationPageinfo.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.annotationPageinfo.setTabText(self.annotationPageinfo.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.label_3.setText(_translate("MainWindow", "analyisPage"))
        self.label_4.setText(_translate("MainWindow", "settingPage"))
        self.label_5.setText(_translate("MainWindow", "helpPage"))
        self.label_6.setText(_translate("MainWindow", "aboutPage"))

        # STACKED PAGE (DEFAULT / CURRENT PAGE) ///////////////
        # Set the page that will be visiable by default when the app is opened
        self.stackedWidget.setCurrentWidget(self.viewerPage)

        # STACKED PAGE NAVIGATION ///////////////////////
        # Using side menu buttons

        # navigating to viewer page
        self.btn_viewer_tab.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.viewerPage))
        # navigating to annotation page
        self.btn_annotation_tab.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.annotationPage))
        # navigating to analysis page
        self.btn_analysis_tab.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.analysisPage))
        # navigating to setting page
        self.btn_setting.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.settingPage))
        # navigating to help page
        self.btn_help.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.helpPage))
        # navigating to about page
        self.btn_about.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.aboutPage))

        self.hspltAnnotationPage.setSizes([self.hspltAnnotationPage.size().height() * 0.7,
                                                self.hspltAnnotationPage.size().height() * 0.3])

        self.vsplitAnnotationPageView.setSizes([self.vsplitAnnotationPageView.size().height()*0.7,
                                                        self.vsplitAnnotationPageView.size().height()*0.3])

        self.hsplitAnnotationPageView.setSizes([self.hsplitAnnotationPageView.size().width()*0.33,
                                                        self.hsplitAnnotationPageView.size().width()*0.33,
                                                        self.hsplitAnnotationPageView.size().width()*0.33])


    def set_slider_range(self, max_range:int, sz_single_step:int=1):
        self.hor_slider.setMinimum(0)
        self.hor_slider.setMaximum(max_range)
        self.hor_slider.setSingleStep(sz_single_step)

    def handleSliderValueChanged(self):
        self.cur_frm = self.hor_slider.value()
        self.line_edit_frm.setText(str(self.cur_frm))