from PySide6 import QtWidgets, QtGui, QtCore, QtOpenGLWidgets


class MainBody(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(MainBody, self).__init__(parent)
        # self.dark_theme = open('dark_theme_mainbody.qss').read()
        # self.setStyleSheet(self.dark_theme)
        self.setupUi()

    def setupUi(self):
        # self = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setObjectName("mainBody")
        self.hlytMainBody = QtWidgets.QHBoxLayout(self)
        self.hlytMainBody.setContentsMargins(5, 5, 0, 0)
        self.hlytMainBody.setSpacing(0)
        self.hlytMainBody.setObjectName("hlytMainBody")
        self.leftMenu = QtWidgets.QWidget(self)
        self.leftMenu.setEnabled(True)
        self.leftMenu.setMinimumSize(QtCore.QSize(25, 0))
        self.leftMenu.setMaximumSize(QtCore.QSize(250, 16777215))
        self.leftMenu.setBaseSize(QtCore.QSize(0, 0))
        self.leftMenu.setObjectName("leftMenu")
        self.vlytLeftMenu = QtWidgets.QVBoxLayout(self.leftMenu)
        self.vlytLeftMenu.setContentsMargins(0, 0, 0, 0)
        self.vlytLeftMenu.setSpacing(0)
        self.vlytLeftMenu.setObjectName("vlytLeftMenu")
        self.leftMenuFrameWrap = QtWidgets.QWidget(self.leftMenu)
        self.leftMenuFrameWrap.setBaseSize(QtCore.QSize(0, 0))
        self.leftMenuFrameWrap.setObjectName("leftMenuFrameWrap")
        self.vlytLeftMenuFrameWrap = QtWidgets.QVBoxLayout(self.leftMenuFrameWrap)
        self.vlytLeftMenuFrameWrap.setContentsMargins(0, 0, 0, 5)
        self.vlytLeftMenuFrameWrap.setSpacing(0)
        self.vlytLeftMenuFrameWrap.setObjectName("vlytLeftMenuFrameWrap")
        self.leftMenuFrameTop = QtWidgets.QFrame(self.leftMenuFrameWrap)
        self.leftMenuFrameTop.setMinimumSize(QtCore.QSize(0, 0))
        self.leftMenuFrameTop.setMaximumSize(QtCore.QSize(30, 16777215))
        self.leftMenuFrameTop.setBaseSize(QtCore.QSize(0, 0))
        self.leftMenuFrameTop.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.leftMenuFrameTop.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftMenuFrameTop.setObjectName("leftMenuFrameTop")
        self.vlytLeftMenuFrameTop = QtWidgets.QVBoxLayout(self.leftMenuFrameTop)
        self.vlytLeftMenuFrameTop.setContentsMargins(0, 0, 0, 0)
        self.vlytLeftMenuFrameTop.setSpacing(0)
        self.vlytLeftMenuFrameTop.setObjectName("vlytLeftMenuFrameTop")
        self.viewerBtn = QtWidgets.QPushButton(self.leftMenuFrameTop)
        self.viewerBtn.setMinimumSize(QtCore.QSize(25, 0))
        self.viewerBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        self.viewerBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.viewerBtn.setStyleSheet(":open{\n"
    "    background-color:#242424;\n"
    "    border-left: 2px solid #f84119;\n"
    "}")
        self.viewerBtn.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resource/icons/viewer-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.viewerBtn.setIcon(icon3)
        self.viewerBtn.setCheckable(True)
        self.viewerBtn.setChecked(True)
        self.viewerBtn.setAutoRepeat(False)
        self.viewerBtn.setDefault(False)
        self.viewerBtn.setObjectName("viewerBtn")
        self.leftMenuBtnGroup = QtWidgets.QButtonGroup(self)
        self.leftMenuBtnGroup.setObjectName("leftMenuBtnGroup")
        self.leftMenuBtnGroup.addButton(self.viewerBtn)
        self.vlytLeftMenuFrameTop.addWidget(self.viewerBtn)
        self.annotationBtn = QtWidgets.QPushButton(self.leftMenuFrameTop)
        self.annotationBtn.setMinimumSize(QtCore.QSize(25, 0))
        self.annotationBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        self.annotationBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.annotationBtn.setStyleSheet(":open{\n"
    "    background-color:#242424;\n"
    "    border-left: 2px solid #f84119;\n"
    "}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resource/icons/tag-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.annotationBtn.setIcon(icon4)
        self.annotationBtn.setCheckable(True)
        self.annotationBtn.setAutoDefault(False)
        self.annotationBtn.setDefault(False)
        self.annotationBtn.setObjectName("annotationBtn")
        self.leftMenuBtnGroup.addButton(self.annotationBtn)
        self.vlytLeftMenuFrameTop.addWidget(self.annotationBtn)
        self.analysisBtn = QtWidgets.QPushButton(self.leftMenuFrameTop)
        self.analysisBtn.setMinimumSize(QtCore.QSize(25, 0))
        self.analysisBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        self.analysisBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.analysisBtn.setStyleSheet(":open{\n"
    "    background-color:#242424;\n"
    "    border-left: 2px solid #f84119;\n"
    "}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resource/icons/scatter-plot-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.analysisBtn.setIcon(icon5)
        self.analysisBtn.setCheckable(True)
        self.analysisBtn.setObjectName("analysisBtn")
        self.leftMenuBtnGroup.addButton(self.analysisBtn)
        self.vlytLeftMenuFrameTop.addWidget(self.analysisBtn)
        self.vlytLeftMenuFrameWrap.addWidget(self.leftMenuFrameTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vlytLeftMenuFrameWrap.addItem(spacerItem)
        self.leftMenuFrameBottom = QtWidgets.QFrame(self.leftMenuFrameWrap)
        self.leftMenuFrameBottom.setMaximumSize(QtCore.QSize(30, 16777215))
        self.leftMenuFrameBottom.setBaseSize(QtCore.QSize(0, 0))
        self.leftMenuFrameBottom.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.leftMenuFrameBottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftMenuFrameBottom.setObjectName("leftMenuFrameBottom")
        self.vlytLeftMenuFrameBottom = QtWidgets.QVBoxLayout(self.leftMenuFrameBottom)
        self.vlytLeftMenuFrameBottom.setContentsMargins(0, 0, 0, 0)
        self.vlytLeftMenuFrameBottom.setSpacing(0)
        self.vlytLeftMenuFrameBottom.setObjectName("vlytLeftMenuFrameBottom")
        self.settingBtn = QtWidgets.QPushButton(self.leftMenuFrameBottom)
        self.settingBtn.setMinimumSize(QtCore.QSize(25, 0))
        self.settingBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        self.settingBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.settingBtn.setStyleSheet(":open{\n"
    "    background-color:#242424;\n"
    "    border-left: 2px solid #f84119;\n"
    "}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resource/icons/settings-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settingBtn.setIcon(icon6)
        self.settingBtn.setCheckable(True)
        self.settingBtn.setObjectName("settingBtn")
        self.leftMenuBtnGroup.addButton(self.settingBtn)
        self.vlytLeftMenuFrameBottom.addWidget(self.settingBtn)
        self.helpBtn = QtWidgets.QPushButton(self.leftMenuFrameBottom)
        self.helpBtn.setMinimumSize(QtCore.QSize(25, 0))
        self.helpBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        self.helpBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.helpBtn.setStyleSheet(":open{\n"
    "    background-color:#242424;\n"
    "    border-left: 2px solid #f84119;\n"
    "}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resource/icons/help-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.helpBtn.setIcon(icon7)
        self.helpBtn.setCheckable(True)
        self.helpBtn.setObjectName("helpBtn")
        self.leftMenuBtnGroup.addButton(self.helpBtn)
        self.vlytLeftMenuFrameBottom.addWidget(self.helpBtn)
        self.aboutBtn = QtWidgets.QPushButton(self.leftMenuFrameBottom)
        self.aboutBtn.setMinimumSize(QtCore.QSize(25, 0))
        self.aboutBtn.setMaximumSize(QtCore.QSize(250, 16777215))
        self.aboutBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.aboutBtn.setStyleSheet(":open{\n"
    "    background-color:#242424;\n"
    "    border-left: 2px solid #f84119;\n"
    "}")
        self.aboutBtn.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resource/icons/info-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.aboutBtn.setIcon(icon8)
        self.aboutBtn.setCheckable(True)
        self.aboutBtn.setChecked(False)
        self.aboutBtn.setAutoDefault(False)
        self.aboutBtn.setDefault(False)
        self.aboutBtn.setObjectName("aboutBtn")
        self.leftMenuBtnGroup.addButton(self.aboutBtn)
        self.vlytLeftMenuFrameBottom.addWidget(self.aboutBtn)
        self.vlytLeftMenuFrameWrap.addWidget(self.leftMenuFrameBottom)
        self.vlytLeftMenu.addWidget(self.leftMenuFrameWrap)
        self.hlytMainBody.addWidget(self.leftMenu)
        selfContent = QtWidgets.QWidget(self)
        selfContent.setObjectName("mainBodyContent")
        selfContent.setStyleSheet("background-color:#242424")
        self.vlytMainBodyContent = QtWidgets.QVBoxLayout(selfContent)
        self.vlytMainBodyContent.setObjectName("vlytMainBodyContent")
        self.stackedWidget = QtWidgets.QStackedWidget(selfContent)
        self.stackedWidget.setObjectName("stackedWidget")
        self.viewerPage = QtWidgets.QWidget()
        self.viewerPage.setObjectName("viewerPage")
        self.label = QtWidgets.QLabel(self.viewerPage)
        self.label.setGeometry(QtCore.QRect(270, 180, 81, 16))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.viewerPage)
        self.annotationPage = QtWidgets.QWidget()
        self.annotationPage.setObjectName("annotationPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.annotationPage)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vlytAnnotationPage = QtWidgets.QVBoxLayout()
        self.vlytAnnotationPage.setSpacing(5)
        self.vlytAnnotationPage.setObjectName("vlytAnnotationPage")
        self.annotationPageControl = QtWidgets.QTabWidget(self.annotationPage)
        self.annotationPageControl.setObjectName("annotationPageControl")
        self.tabAnnotationPageControlMain = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabAnnotationPageControlMain.sizePolicy().hasHeightForWidth())
        self.tabAnnotationPageControlMain.setSizePolicy(sizePolicy)
        self.tabAnnotationPageControlMain.setObjectName("tabAnnotationPageControlMain")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabAnnotationPageControlMain)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hlytPlayControls = QtWidgets.QHBoxLayout()
        self.hlytPlayControls.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.hlytPlayControls.setSpacing(5)
        self.hlytPlayControls.setObjectName("hlytPlayControls")
        self.horizontalSlider = QtWidgets.QSlider(self.tabAnnotationPageControlMain)
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.SizeHorCursor))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.hlytPlayControls.addWidget(self.horizontalSlider)
        self.hlinePlayControl1 = QtWidgets.QFrame(self.tabAnnotationPageControlMain)
        self.hlinePlayControl1.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.hlinePlayControl1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.hlinePlayControl1.setObjectName("hlinePlayControl1")
        self.hlytPlayControls.addWidget(self.hlinePlayControl1)
        self.lineEditFrame = QtWidgets.QLineEdit(self.tabAnnotationPageControlMain)
        self.lineEditFrame.setObjectName("lineEditFrame")
        self.hlytPlayControls.addWidget(self.lineEditFrame)
        self.hlinePlayControl2 = QtWidgets.QFrame(self.tabAnnotationPageControlMain)
        self.hlinePlayControl2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.hlinePlayControl2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.hlinePlayControl2.setObjectName("hlinePlayControl2")
        self.hlytPlayControls.addWidget(self.hlinePlayControl2)
        self.btnStart = QtWidgets.QPushButton(self.tabAnnotationPageControlMain)
        self.btnStart.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnStart.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("resource/icons/player-control-skip-to-start-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnStart.setIcon(icon9)
        self.btnStart.setObjectName("btnStart")
        self.hlytPlayControls.addWidget(self.btnStart)
        self.btnStepBwd = QtWidgets.QPushButton(self.tabAnnotationPageControlMain)
        self.btnStepBwd.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnStepBwd.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("resource/icons/player-control-rewind-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnStepBwd.setIcon(icon10)
        self.btnStepBwd.setIconSize(QtCore.QSize(16, 16))
        self.btnStepBwd.setObjectName("btnStepBwd")
        self.hlytPlayControls.addWidget(self.btnStepBwd)
        self.btnPause = QtWidgets.QPushButton(self.tabAnnotationPageControlMain)
        self.btnPause.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPause.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("resource/icons/player-control-pause-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPause.setIcon(icon11)
        self.btnPause.setObjectName("btnPause")
        self.hlytPlayControls.addWidget(self.btnPause)
        self.btnPlay = QtWidgets.QPushButton(self.tabAnnotationPageControlMain)
        self.btnPlay.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPlay.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("resource/icons/player-control-play-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPlay.setIcon(icon12)
        self.btnPlay.setObjectName("btnPlay")
        self.hlytPlayControls.addWidget(self.btnPlay)
        self.btnStepFwd = QtWidgets.QPushButton(self.tabAnnotationPageControlMain)
        self.btnStepFwd.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnStepFwd.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("resource/icons/player-control-fast-forward-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnStepFwd.setIcon(icon13)
        self.btnStepFwd.setObjectName("btnStepFwd")
        self.hlytPlayControls.addWidget(self.btnStepFwd)
        self.btnEnd = QtWidgets.QPushButton(self.tabAnnotationPageControlMain)
        self.btnEnd.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnEnd.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("resource/icons/player-control-end-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnEnd.setIcon(icon14)
        self.btnEnd.setObjectName("btnEnd")
        self.hlytPlayControls.addWidget(self.btnEnd)
        self.hlytPlayControls.setStretch(0, 9)
        self.horizontalLayout_2.addLayout(self.hlytPlayControls)
        self.annotationPageControl.addTab(self.tabAnnotationPageControlMain, "")
        self.tabAnnotationControlSub = QtWidgets.QWidget()
        self.tabAnnotationControlSub.setObjectName("tabAnnotationControlSub")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tabAnnotationControlSub)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.hlytViewConfig = QtWidgets.QHBoxLayout()
        self.hlytViewConfig.setObjectName("hlytViewConfig")
        self.comboBoxSensorConfig = QtWidgets.QComboBox(self.tabAnnotationControlSub)
        self.comboBoxSensorConfig.setObjectName("comboBoxSensorConfig")
        self.hlytViewConfig.addWidget(self.comboBoxSensorConfig)
        self.comboBoxDtctConfig = QtWidgets.QComboBox(self.tabAnnotationControlSub)
        self.comboBoxDtctConfig.setObjectName("comboBoxDtctConfig")
        self.hlytViewConfig.addWidget(self.comboBoxDtctConfig)
        self.comboBoxObjConfig = QtWidgets.QComboBox(self.tabAnnotationControlSub)
        self.comboBoxObjConfig.setObjectName("comboBoxObjConfig")
        self.hlytViewConfig.addWidget(self.comboBoxObjConfig)
        self.comboBoxViewConfig = QtWidgets.QComboBox(self.tabAnnotationControlSub)
        self.comboBoxViewConfig.setObjectName("comboBoxViewConfig")
        self.hlytViewConfig.addWidget(self.comboBoxViewConfig)
        self.btnPalette = QtWidgets.QPushButton(self.tabAnnotationControlSub)
        self.btnPalette.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPalette.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("resource/icons/palette-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPalette.setIcon(icon15)
        self.btnPalette.setObjectName("btnPalette")
        self.hlytViewConfig.addWidget(self.btnPalette)
        self.btnSaveConfig = QtWidgets.QPushButton(self.tabAnnotationControlSub)
        self.btnSaveConfig.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("resource/icons/save-document-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSaveConfig.setIcon(icon16)
        self.btnSaveConfig.setObjectName("btnSaveConfig")
        self.hlytViewConfig.addWidget(self.btnSaveConfig)
        self.btnLoadConfig = QtWidgets.QPushButton(self.tabAnnotationControlSub)
        self.btnLoadConfig.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("resource/icons/open-document-96.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnLoadConfig.setIcon(icon17)
        self.btnLoadConfig.setObjectName("btnLoadConfig")
        self.hlytViewConfig.addWidget(self.btnLoadConfig)
        self.hlytViewConfig.setStretch(0, 1)
        self.hlytViewConfig.setStretch(1, 1)
        self.hlytViewConfig.setStretch(2, 1)
        self.hlytViewConfig.setStretch(3, 1)
        self.horizontalLayout_4.addLayout(self.hlytViewConfig)
        self.annotationPageControl.addTab(self.tabAnnotationControlSub, "")
        self.vlytAnnotationPage.addWidget(self.annotationPageControl)
        self.hspltAnnotationPage = QtWidgets.QSplitter(self.annotationPage)
        self.hspltAnnotationPage.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.hspltAnnotationPage.setChildrenCollapsible(False)
        self.hspltAnnotationPage.setObjectName("hspltAnnotationPage")
        self.vsplitAnnotationPageView = QtWidgets.QSplitter(self.hspltAnnotationPage)
        self.vsplitAnnotationPageView.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.vsplitAnnotationPageView.setChildrenCollapsible(False)
        self.vsplitAnnotationPageView.setObjectName("vsplitAnnotationPageView")
        self.openGLWidget_4 = QtOpenGLWidgets.QOpenGLWidget(self.vsplitAnnotationPageView)
        self.openGLWidget_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.openGLWidget_4.setMouseTracking(False)
        self.openGLWidget_4.setObjectName("openGLWidget_4")
        self.hsplitAnnotationPageView = QtWidgets.QSplitter(self.vsplitAnnotationPageView)
        self.hsplitAnnotationPageView.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.hsplitAnnotationPageView.setChildrenCollapsible(False)
        self.hsplitAnnotationPageView.setObjectName("hsplitAnnotationPageView")
        self.openGLWidget = QtOpenGLWidgets.QOpenGLWidget(self.hsplitAnnotationPageView)
        self.openGLWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.openGLWidget.setObjectName("openGLWidget")
        self.openGLWidget_2 = QtOpenGLWidgets.QOpenGLWidget(self.hsplitAnnotationPageView)
        self.openGLWidget_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.openGLWidget_2.setObjectName("openGLWidget_2")
        self.openGLWidget_3 = QtOpenGLWidgets.QOpenGLWidget(self.hsplitAnnotationPageView)
        self.openGLWidget_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.openGLWidget_3.setObjectName("openGLWidget_3")
        self.annotationPageinfo = QtWidgets.QTabWidget(self.hspltAnnotationPage)
        self.annotationPageinfo.setObjectName("annotationPageinfo")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.annotationPageinfo.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.annotationPageinfo.addTab(self.tab_4, "")
        self.vlytAnnotationPage.addWidget(self.hspltAnnotationPage)
        self.vlytAnnotationPage.setStretch(1, 9)
        self.verticalLayout_2.addLayout(self.vlytAnnotationPage)
        self.stackedWidget.addWidget(self.annotationPage)
        self.analysisPage = QtWidgets.QWidget()
        self.analysisPage.setObjectName("analysisPage")
        self.label_3 = QtWidgets.QLabel(self.analysisPage)
        self.label_3.setGeometry(QtCore.QRect(290, 150, 131, 16))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.analysisPage)
        self.settingPage = QtWidgets.QWidget()
        self.settingPage.setObjectName("settingPage")
        self.label_4 = QtWidgets.QLabel(self.settingPage)
        self.label_4.setGeometry(QtCore.QRect(400, 190, 121, 16))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.settingPage)
        self.helpPage = QtWidgets.QWidget()
        self.helpPage.setObjectName("helpPage")
        self.label_5 = QtWidgets.QLabel(self.helpPage)
        self.label_5.setGeometry(QtCore.QRect(260, 230, 81, 16))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.helpPage)
        self.aboutPage = QtWidgets.QWidget()
        self.aboutPage.setObjectName("aboutPage")
        self.label_6 = QtWidgets.QLabel(self.aboutPage)
        self.label_6.setGeometry(QtCore.QRect(420, 260, 91, 16))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.aboutPage)
        self.vlytMainBodyContent.addWidget(self.stackedWidget)
        self.hlytMainBody.addWidget(selfContent)
        self.rightMenu = QtWidgets.QWidget(self)
        self.rightMenu.setObjectName("rightMenu")
        self.hlytMainBody.addWidget(self.rightMenu)

        self.stackedWidget.setCurrentIndex(1)
        self.annotationPageControl.setCurrentIndex(1)
        self.annotationPageinfo.setCurrentIndex(0)
        # self.vlytCentralWidget.addWidget(self)
        # self.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(self)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        # self.menubar.setObjectName("menubar")
        # self.menuFile = QtWidgets.QMenu(self.menubar)
        # self.menuFile.setObjectName("menuFile")
        # self.menuHelp = QtWidgets.QMenu(self.menubar)
        # self.menuHelp.setObjectName("menuHelp")
        # self.menuTools = QtWidgets.QMenu(self.menubar)
        # self.menuTools.setObjectName("menuTools")
        # self.menuVEST = QtWidgets.QMenu(self.menubar)
        # self.menuVEST.setObjectName("menuVEST")
        # self.menuConfiguration = QtWidgets.QMenu(self.menuVEST)
        # self.menuConfiguration.setObjectName("menuConfiguration")
        # self.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(self)
        # self.statusbar.setObjectName("statusbar")
        # self.setStatusBar(self.statusbar)
        # self.toolBar = QtWidgets.QToolBar(self)
        # self.toolBar.setObjectName("toolBar")
        # self.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        # self.actionOpenFile = QtGui.QAction(self)
        # self.actionOpenFile.setObjectName("actionOpenFile")
        # self.actionQuit = QtGui.QAction(self)
        # self.actionQuit.setObjectName("actionQuit")
        # self.actionAbout = QtGui.QAction(self)
        # self.actionAbout.setObjectName("actionAbout")
        # self.actionAbout_VEST = QtGui.QAction(self)
        # self.actionAbout_VEST.setObjectName("actionAbout_VEST")
        # self.actionQuit_VEST = QtGui.QAction(self)
        # self.actionQuit_VEST.setObjectName("actionQuit_VEST")
        # self.actionPlugins = QtGui.QAction(self)
        # self.actionPlugins.setObjectName("actionPlugins")
        # self.actionOpen = QtGui.QAction(self)
        # self.actionOpen.setObjectName("actionOpen")
        # self.actionSave = QtGui.QAction(self)
        # self.actionSave.setObjectName("actionSave")
        # self.menuFile.addAction(self.actionOpenFile)
        # self.menuHelp.addAction(self.actionAbout)
        # self.menuConfiguration.addAction(self.actionOpen)
        # self.menuConfiguration.addAction(self.actionSave)
        # self.menuVEST.addAction(self.actionAbout_VEST)
        # self.menuVEST.addAction(self.actionPlugins)
        # self.menuVEST.addAction(self.menuConfiguration.menuAction())
        # self.menuVEST.addAction(self.actionQuit_VEST)
        # self.menubar.addAction(self.menuVEST.menuAction())
        # self.menubar.addAction(self.menuFile.menuAction())
        # self.menubar.addAction(self.menuTools.menuAction())
        # self.menubar.addAction(self.menuHelp.menuAction())

    def retranslateUi(self, _translate):
        self.viewerBtn.setText(_translate("MainWindow", "Viewer"))
        self.annotationBtn.setText(_translate("MainWindow", "Annotation"))
        self.analysisBtn.setText(_translate("MainWindow", "Analysis"))
        self.settingBtn.setText(_translate("MainWindow", "Setting"))
        self.helpBtn.setText(_translate("MainWindow", "Help"))
        self.aboutBtn.setText(_translate("MainWindow", "About"))
        self.label.setText(_translate("MainWindow", "viewerPage"))
        self.annotationPageControl.setTabText(self.annotationPageControl.indexOf(self.tabAnnotationPageControlMain), _translate("MainWindow", "Play Controls"))
        self.annotationPageControl.setTabText(self.annotationPageControl.indexOf(self.tabAnnotationControlSub), _translate("MainWindow", "View Configuration"))
        self.annotationPageinfo.setTabText(self.annotationPageinfo.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.annotationPageinfo.setTabText(self.annotationPageinfo.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.label_3.setText(_translate("MainWindow", "analyisPage"))
        self.label_4.setText(_translate("MainWindow", "settingPage"))
        self.label_5.setText(_translate("MainWindow", "helpPage"))
        self.label_6.setText(_translate("MainWindow", "aboutPage"))

        # STACKED PAGE (DEFAULT / CURRENT PAGE) ///////////////
        # Set the page that will be visiable by default when the app is opened
        self.stackedWidget.setCurrentWidget(self.viewerPage)

        # STACKED PAGE NAVIGATION ///////////////////////
        # Using side menu buttons

        # navigating to viewer page
        self.viewerBtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.viewerPage))
        # navigating to annotation page
        self.annotationBtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.annotationPage))
        # navigating to analysis page
        self.analysisBtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.analysisPage))
        # navigating to setting page
        self.settingBtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.settingPage))
        # navigating to help page
        self.helpBtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.helpPage))
        # navigating to about page
        self.aboutBtn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.aboutPage))

        self.hspltAnnotationPage.setSizes([self.hspltAnnotationPage.size().height() * 0.7,
                                                self.hspltAnnotationPage.size().height() * 0.3])

        self.vsplitAnnotationPageView.setSizes([self.vsplitAnnotationPageView.size().height()*0.7,
                                                        self.vsplitAnnotationPageView.size().height()*0.3])

        self.hsplitAnnotationPageView.setSizes([self.hsplitAnnotationPageView.size().width()*0.33,
                                                        self.hsplitAnnotationPageView.size().width()*0.33,
                                                        self.hsplitAnnotationPageView.size().width()*0.33])