# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide6.QtWidgets import QApplication, QMainWindow
from PySide6 import QtCore, QtGui, QtWidgets

from header import Header
from mainbody import MainBody

class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setupUi()
        self.setWindowTitle("VEST")
        self.dark_theme = open('dark_theme.qss').read()
        self.setStyleSheet(self.dark_theme)


    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.vlytCentralWidget = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vlytCentralWidget.setContentsMargins(0, 0, 0, 0)
        self.vlytCentralWidget.setSpacing(2)
        self.vlytCentralWidget.setObjectName("vlytCentralWidget")
        self.header = Header(parent=self.centralwidget)
        self.vlytCentralWidget.addWidget(self.header)
        
        self.mainBody = MainBody(parent=self.centralwidget)

        self.vlytCentralWidget.addWidget(self.mainBody)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuVEST = QtWidgets.QMenu(self.menubar)
        self.menuVEST.setObjectName("menuVEST")
        self.menuConfiguration = QtWidgets.QMenu(self.menuVEST)
        self.menuConfiguration.setObjectName("menuConfiguration")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(self)
        self.toolBar.setObjectName("toolBar")
        self.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionOpenFile = QtGui.QAction(self)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionQuit = QtGui.QAction(self)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(self)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_VEST = QtGui.QAction(self)
        self.actionAbout_VEST.setObjectName("actionAbout_VEST")
        self.actionQuit_VEST = QtGui.QAction(self)
        self.actionQuit_VEST.setObjectName("actionQuit_VEST")
        self.actionPlugins = QtGui.QAction(self)
        self.actionPlugins.setObjectName("actionPlugins")
        self.actionOpen = QtGui.QAction(self)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(self)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpenFile)
        self.menuHelp.addAction(self.actionAbout)
        self.menuConfiguration.addAction(self.actionOpen)
        self.menuConfiguration.addAction(self.actionSave)
        self.menuVEST.addAction(self.actionAbout_VEST)
        self.menuVEST.addAction(self.actionPlugins)
        self.menuVEST.addAction(self.menuConfiguration.menuAction())
        self.menuVEST.addAction(self.actionQuit_VEST)
        self.menubar.addAction(self.menuVEST.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header.retranslateUi(_translate)
        self.mainBody.retranslateUi(_translate)

        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuVEST.setTitle(_translate("MainWindow", "VEST"))
        self.menuConfiguration.setTitle(_translate("MainWindow", "Configuration"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpenFile.setText(_translate("MainWindow", "Open"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "UI Tour"))
        self.actionAbout_VEST.setText(_translate("MainWindow", "About VEST"))
        self.actionQuit_VEST.setText(_translate("MainWindow", "Quit VEST"))
        self.actionPlugins.setText(_translate("MainWindow", "Plugins"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

        # SLIDABLE LEFT MENU /////////////////////
        self.header.menuBtn.clicked.connect(lambda: self.slideLeftMenu())

    ###################################################
    # Slide left menu
    ##################################################
    def slideLeftMenu(self):
        # Get current left menu width
        width = self.mainBody.leftMenuFrameTop.width()
        new_width = 0
        # If minimized
        if width >= 120:
            # Expand menu
            new_width = 30
            # print(1)
        # If maximized
        else:
            # Resotre menu
            new_width = 120
            # print(2)

        # Animate the transition
        self.animation_leftmenutop = QtCore.QPropertyAnimation(self.mainBody.leftMenuFrameTop, b"minimumWidth")  # Animate minimimWidth
        self.animation_leftmenutop.setDuration(250)
        # print("width:{}, new_width:{}".format(width, new_width))
        self.animation_leftmenutop.setStartValue(width)     # start value is the current menu width
        self.animation_leftmenutop.setEndValue(new_width)   # end value is the new menu width
        self.animation_leftmenutop.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
        #self.animation.start()

        self.animation_leftmenubottom = QtCore.QPropertyAnimation(self.mainBody.leftMenuFrameBottom, b"minimumWidth")  # Animate minimimWidth
        self.animation_leftmenubottom.setDuration(250)
        # print("width:{}, new_width:{}".format(width, new_width))
        self.animation_leftmenubottom.setStartValue(width)     # start value is the current menu width
        self.animation_leftmenubottom.setEndValue(new_width)   # end value is the new menu width
        self.animation_leftmenubottom.setEasingCurve(QtCore.QEasingCurve.InOutQuart)

        self.animation_group_leftmenu = QtCore.QParallelAnimationGroup()
        self.animation_group_leftmenu.addAnimation(self.animation_leftmenutop)
        self.animation_group_leftmenu.addAnimation(self.animation_leftmenubottom)

        self.animation_group_leftmenu.start()

